backend:
  name: github
  repo: varunzxzx/nextjs-blog   # Path to your Github/Gitlab repository
  branch: master    # Branch to update
  base_url: https://shimmering-excited-mulberry.glitch.me # Path to ext auth provider
media_folder: public/images
collections:
- name: "posts"
  label: "Posts"
  folder: "posts"
  create: true
  fields:
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Body", name: "body", widget: "markdown"}