backend:
  name: github
  repo: varunzxzx/nextjs-blog
  open_authoring: true
  base_url: https://nextjs-blog-seven-jet.vercel.app
publish_mode: editorial_workflow
media_folder: public/images
collections:
- name: "posts"
  label: "Posts"
  folder: "posts"
  create: true
  fields:
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Body", name: "body", widget: "markdown"}