backend:
    name: git-gateway
    branch: master
media_folder: public/images
collections:
- name: "posts"
  label: "Posts"
  files:
    - label: "Pre Rendering"
      name: "pre-rendering"
      file: "posts/pre-rendering.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}