backend:
    name: git-gateway
    branch: master
media_folder: public/images
collections:
- name: "posts"
  label: "Posts"
  folder: "posts"
  create: true
  fields:
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Body", name: "body", widget: "markdown"}